name: Crawl AN GIANG 3 EPG

on:
  schedule:
    # Runs at 01:00 Asia/Ho_Chi_Minh (UTC+7) -> 18:00 UTC previous day
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run crawler
        run: |
          python atv3kg2.py

      - name: Commit and push XML (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add atv3kg2.xml || true
          if ! git diff --cached --quiet; then
            git commit -m "Update atv3kg2.xml (EPG) [skip ci]" || true
            git push origin HEAD:main
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
