name: BRT HTV EPG Crawler

on:
  schedule:
    - cron: "0 18 * * *"   # chạy lúc 1h sáng (UTC+7)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml lxml_html_clean pytz

      - name: Run crawler for BRT HTV
        run: |
          echo "=== RUNNING CRAWLER (BRT HTV) ==="
          python brthtv.py
          echo "=== DONE ==="

      - name: Commit and push results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add brthtv.xml
          git commit -m "Update brthtv.xml [auto]" || echo "No changes to commit"
          git push
