name: BRT HTV EPG Crawler (Playwright)

on:
  schedule:
    - cron: "0 18 * * *"   # 01:00 Hà Nội (UTC+7)
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright beautifulsoup4 pytz

      - name: Install Playwright browsers
        run: |
          python -m playwright install --with-deps chromium

      - name: Run brthtv crawler
        run: |
          echo "=== RUNNING CRAWLER (BRT) ==="
          python brthtv.py
          echo "=== DONE ==="

      - name: Commit and push results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add brthtv.xml
          git commit -m "Update brthtv.xml [auto]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main
