name: Crawl BRT HTV EPG
on:
  schedule:
    - cron: '0 18 * * *'  # chạy lúc 1h sáng VN (18h UTC)
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install selenium beautifulsoup4 lxml
          sudo apt-get update
          sudo apt-get install -y chromium-browser
      - name: Run crawler
        run: python brthtv.py
      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add brthtv.xml
          git commit -m "Update BRT HTV EPG"
          git push
